version: "3.8"

services:
  siva-webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7777:8080"
    environment:
      - JAVA_OPTS=-Xmx2g
      - SPRING_AUTOCONFIGURE_EXCLUDE=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - SIVA_EUROPE_SIGNATUREPOLICY_DEFAULTPOLICY=POLv3
      - SIVA_TSL_LOADER_LOADFROMCACHE=false
    networks:
      default:
        aliases:
          - siva.localhost
    volumes:
      - ./docker/logback.xml:/etc/siva-webapp/logback.xml
    restart: unless-stopped

networks:
  default:
    driver: bridge
